#!/usr/bin/env bash
set -aeuo pipefail

rsync -avzP \
  src/wp-content/mu-plugins/ root@yaoyingying.com:/var/www/yaoin.net/wp-content/mu-plugins/


rsync -avzP \
  src/wp-content/themes/ root@yaoyingying.com:/var/www/yaoin.net/wp-content/themes/

