#!/usr/bin/env bash
set -aeuo pipefail

rsync -avzP \
  src/wp-content/themes/ root@yaoin.net:/var/www/yaoin.net/wp-content/themes/

# PWA TEST
npm run build
rsync -avzP dist/ root@yaoin.net:/var/www/yaoin.net/
