#!/usr/bin/env bash
set -aeuo pipefail

# create the dotenv file if it doesn't exist
if [ ! -f .env ]; then
  cp .env.default .env
fi

source .env

VERSION=$(cat VERSION)

FILES="-f ./docker-compose.yml"

docker-compose --verbose $FILES $@
