version: "3.1"

services:
  wordpress:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_wordpress_apache
    env_file: .env
    restart: always
    ports:
      - "${WORDPRESS_HTTP_PORT}:80"
    environment:
      - PUID=${DOCKER_HOST_UID}  # Replace with your UID
      - PGID=${DOCKER_HOST_GID}  # Replace with your GID
      - WORDPRESS_DEBUG=1
    depends_on:
      - cache
      - wordpress_db
    volumes:
      - wordpress-uploads:/var/www/html/wp-content/uploads
      - ./src:/var/www/html

  wordpress_db:
    image: mysql:8
    restart: always
    # command: "--log-error-suppression-list=MY-013360"
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=root --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      - MYSQL_DATABASE=domain
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - wordpress-db:/var/lib/mysql
      - ./transfer:/docker-entrypoint-initdb.d:delegated

  cache:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_cache
    restart: always
    volumes:
      - wordpress-cache:/data

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=wordpress_db
    ports:
      - 18080:8080


volumes:
  wordpress-uploads:
  wordpress-db:
  wordpress-cache:

