version: "3.1"

services:
  wordpress:
    container_name: ${COMPOSE_PROJECT_NAME}_wordpress_apache
    restart: always
    ports:
      - "${WORDPRESS_HTTP_PORT}:80"
    depends_on:
      - cache
      - wordpress_db
    

  wordpress_db:
    image: mysql:8
    restart: always
    # command: "--log-error-suppression-list=MY-013360"
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=root --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      - MYSQL_DATABASE=domain
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - wordpress-db:/var/lib/mysql
      - ./transfer:/docker-entrypoint-initdb.d:delegated

  cache:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_cache
    restart: always
    volumes:
      - wordpress-cache:/data


volumes:
  wordpress-uploads:
  wordpress-db:
  wordpress-cache:

