#!/usr/bin/env bash
set -aeuo pipefail


# --exclude 'wp-content'
rsync -avzP  \
  --exclude 'favicon.ico' \
  --exclude 'wp-content' \
  --exclude 'vendor' \
  --exclude '*.swp' \
  ubuntu@yaoyingying.com:/var/www/yaoyingying.com/ src/

# languages
rsync -avzP  \
  ubuntu@yaoyingying.com:/var/www/yaoyingying.com/wp-content/languages/ src/wp-content/languages/


rsync -avzP  \
  ubuntu@yaoyingying.com:/var/www/yaoyingying.com/wp-content/mu-plugins/ src/wp-content/mu-plugins/

rsync -avzP  \
  ubuntu@yaoyingying.com:/var/www/yaoyingying.com/wp-content/plugins/ src/wp-content/plugins/

rsync -avzP  \
  ubuntu@yaoyingying.com:/var/www/yaoyingying.com/wp-content/themes/ src/wp-content/themes/
